# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: name_server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11name_server.proto\x12\nnameserver\"=\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"%\n\x11GetAddressRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"5\n\x12GetAddressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\x9a\x01\n\x0fServidorNombres\x12:\n\x08Register\x12\x1b.nameserver.RegisterRequest\x1a\x11.nameserver.Empty\x12K\n\nGetAddress\x12\x1d.nameserver.GetAddressRequest\x1a\x1e.nameserver.GetAddressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=33
  _globals['_REGISTERREQUEST']._serialized_end=94
  _globals['_EMPTY']._serialized_start=96
  _globals['_EMPTY']._serialized_end=103
  _globals['_GETADDRESSREQUEST']._serialized_start=105
  _globals['_GETADDRESSREQUEST']._serialized_end=142
  _globals['_GETADDRESSRESPONSE']._serialized_start=144
  _globals['_GETADDRESSRESPONSE']._serialized_end=197
  _globals['_SERVIDORNOMBRES']._serialized_start=200
  _globals['_SERVIDORNOMBRES']._serialized_end=354
# @@protoc_insertion_point(module_scope)
